### ISSUE TITLE
Unable to pull shared project from collaboration server using neoload-controller

### ISSUE THREAD

**Issue by wex-rcyr** [Neotys-Labs/Docker#6]
When we try to start up the docker image with the following configured parms we are seeing this error after the project is checked out of collaboration server (AzureDevops).

- Checking out project: Sample_Project
**_com.neotys.nl.l.a.n: Item '/DevOps/_git/neoload-demo/Sample_Project/8_6/project' does not exist_**

- options being passed in (via docker-compose.yml):  
   - COLLAB_URL=https://dev.azure.com/neload-demo      
   - COLLAB_LOGIN=<user>:<PWD>     
   - PROJECT_NAME=Sample_Project      
   - SCENARIO=demo-scenario   
   - LEASE_SERVER=NLWEB
   - NEOLOADWEB_TOKEN=<token>     
   - VU_MAX=50            
   - DURATION_MAX=1     
   - PUBLISH_RESULT=NTS

The problem seems to be with something is expecting project to be in the a path that is not provided.
Item '/DevOps/_git/neolaod-demo/Sample_Project/8_6/project' does not exist
in this path we are not providing the /8_6/project and we believe this may be why the checkout is failing every time.

Also the collaboration project  WAS published from NeoLoad, so we are expecting the its setting up the project correctly.

We are also using the latest docker image as of 10/6/2022

**Comment by stephanemartin** [comment]
Hello, 
What is your protocol of collaborative server ?  (Git or SVN)

**Comment by wex-rcyr** [comment]
GIT

**Comment by stephanemartin** [comment]
The NeoLoadCmd can't checkout project from git in command line argument.
Docker environment variable trigs NeoLoadCmd with corresponding arguments.
I know that is missing. I notify again our PM to add this little feature.

Best regards.

**Comment by wex-rcyr** [comment]
ok, with that now I am running into a new issue when trying to use the neoload in the docker image

Launching NeoLoad with following parameters -noGUI -project ../projects/WOLNG_Online_Vivid/WOLNG_Performance_Scripts/WOLNG_Performance_Scripts.nlp -launch 5 User Run -leaseServer nlweb -nlwebToken d2b39fcf3928348e22c5f40cdf16d72a98cebaf6dd0f785d -leaseLicense 50:1
No suitable Java Virtual Machine could be found on your system.
The version of the JVM must be at least 1.8.0_252.
Please define INSTALL4J_JAVA_HOME to point to a suitable JVM.

**Comment by stephanemartin** [comment]
I don't know how do you launch your container. When I launch that it founds java.
```
docker run -it --entrypoint="" --rm neotys/neoload-controller /home/neoload/neoload/bin/NeoLoadCmd --noGUI
Logging to /home/neoload/.neotys/neoload/v9.0/logs, as user: neoload
Launching agents
RealBrowser is not enabled
Agents launched
NeoLoad started

```

**Comment by wex-rcyr** [comment]
I am using a docker-compose file to run the docker file.  The compose if just setting the environment variables for me so it should be using the same docker entry point 

ENTRYPOINT ["/bin/sh", "/home/neoload/entrypoint.sh"]

**Comment by wex-rcyr** [comment]
I was able to get it working ... Thank you for your help
